---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisesayings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisesayings
  template:
    metadata:
      labels:
        app: wisesayings
    spec:
      containers:
      - name: wisesayings
        image: georgeniece/wisesayings:v0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
